version: "3"

services:
  dagster_postgresql:
    image: postgres:11
    container_name: dagster_postgresql
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    networks:
      - ai_kickstart_network

  dagster_grpc_server:
    build:
      context: ..
      dockerfile: dagster_grpc.Dockerfile
    container_name: dagster_grpc_server
    image: dagster_grpc_server_image
#    restart: always
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      DAGSTER_CURRENT_IMAGE: "dagster_grpc_server_image"
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - ai_kickstart_network
    healthcheck:
      test: [ "CMD", "ls", "-l", "/proc/1/exe" ]
      interval: 10s
      timeout: 5s
      retries: 5

  dagster_webserver:
    build:
      context: ..
      dockerfile: dagster_daemon.Dockerfile
      args:
        - BUILD_ENV=$BUILD_ENV
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: dagster_webserver
    expose:
      - 3000
    ports:
      - 3000:3000

    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      DAGSTER_CURRENT_IMAGE: "dagster_grpc_server_image"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    depends_on:
      dagster_grpc_server:
        condition: service_healthy
    networks:
      - ai_kickstart_network

  dagster_daemon:
    build:
      context: ..
      dockerfile: dagster_daemon.Dockerfile
      args:
        - BUILD_ENV=$BUILD_ENV
    entrypoint:
      - dagster-daemon
      - run
      - -w
      - workspace.yaml
    container_name: dagster_daemon
    restart: on-failure

    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    depends_on:
      dagster_grpc_server:
        condition: service_healthy
    networks:
      - ai_kickstart_network
