# This docker-compose file provides an ephemeral MLflow and lakeFS instance for
# development purposes.

version: "3"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.2
    ports:
      - 5000:5000
    command: mlflow server --host 0.0.0.0 --port 5000

  lakefs:
    image: treeverse/lakefs:1.12.1
    ports:
      - 8000:8000
    environment:
      LAKEFS_INSTALLATION_USER_NAME: "quickstart"
      LAKEFS_INSTALLATION_ACCESS_KEY_ID: "AKIAIOSFOLQUICKSTART"
      LAKEFS_INSTALLATION_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      LAKEFS_DATABASE_TYPE: "local"
      LAKEFS_AUTH_ENCRYPT_SECRET_KEY: "THIS_MUST_BE_CHANGED_IN_PRODUCTION"
      LAKEFS_BLOCKSTORE_TYPE: "local"
